version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "20:00"
      timezone: "America/Vancouver"
    reviewers:
      - "Nismit"
