name = "Humble"
license = "MIT"
licenselink = "https://github.com/Nismit/humble/blob/master/LICENSE"
description = "A minimal Hugo theme"
homepage = "http://example.com/"
tags = ["blog"]
features = ["responsive", "syntax highlight", "ogp", "twitter cards"]
min_version = "0.55.4"

[author]
  name = "Nismit"
  homepage = "https://nismit.me"
